const data = [
    {
        "cart_items": [
            {
                "id": 21,
                "category": "Televisions",
                "name": "Polystar 55 Inch Android Smart 4k Ultra HD LED TV",
                "description": "The Polystar offers a sophisticated series of UHD Smart TV. The High performance multi-core processors will give you unparalleled Smart TV performance and brilliant 4K UHD picture quality. This is coupled with great connectivity options and a premium design.\r\nThe HDMI inputs is sure to deliver a superior picture and sound quality to your living space while, the USB 3.0 ensures that your downloaded movies and content produces a crystal clear and crisp picture quality.",
                "price": 230000,
                "image": "http://127.0.0.1:8000/media/images/Polystar_55_Inch_Android_Smart_4k_Ultra_HD_LED_TV.jpg",
                "date_created": "2022-07-08T14:35:43.407506Z",
                "itemCount": 1
            },
            {
                "id": 20,
                "category": "Televisions",
                "name": "Hisense 58''Smart UHD 4K TV+Netflix,Youtube",
                "description": "The ultra hd smart led tv58A7100 58\" TV is manufactured by Hisense and was added around October 2020. This version of the TV comes in Screen Size : 58 Inch , Display Technology : LED , Special Features : Internet Connectivity , Special Features : Without 3D , Special Features : Smart TV , Refresh Rate : 50 HZ , Display Resolution : Ultra HD (4K).High Dynamic RangeYou’ll be refreshed by what you see  whites look brighter, blacks look darker and colors look more vibrant.",
                "price": 274900,
                "image": "http://127.0.0.1:8000/media/images/Hisense_58Smart_UHD_4K_TVNetflixYoutube.jpg",
                "date_created": "2022-07-08T14:33:00.247684Z",
                "itemCount": 1
            },
            {
                "id": 19,
                "category": "Televisions",
                "name": "Samsung 50 Inch Crystal Ultra HD AU8000 Smart TV",
                "description": "The TU has built-in Wi-Fi, Ethernet, and AirPlay 2 connectivity to allow access to your favorite apps and internet-based content, plus content sharing and screen mirroring with your other smart devices such as your smartphone or tablet. A full web browser is also onboard, allowing you to view full websites rather than mobile versions. HDMI inputs allow you to connect high-definition video sources, and a USB port is also onboard for connecting multimedia peripherals like flash drives. The TV can",
                "price": 314000,
                "image": "http://127.0.0.1:8000/media/images/Samsung_50_Inch_Crystal_Ultra_HD_AU8000_Smart_TV.jpg",
                "date_created": "2022-07-08T14:26:40.061361Z",
                "itemCount": 1
            }
        ],
        "cost": 818900.0,
        "customer": "michaelikoko.o@gmail.com",
        "status": "pending",
        "order_number": "4369935704",
        "date_ordered": "2022-07-26T17:52:46.359748Z"
    },
    {
        "cart_items": [
            {
                "id": 11,
                "category": "Accessories",
                "name": "12inch 3D Mobile Phone Screen Magnifier HD Video A",
                "description": "Feature:1. HD display screen: Fresnel mirror screen adopts optical HD zoom technology, which can enlarge HD by 3 to 4 times, effectively preventing radiation generated by mobile phone.2. Sliding design: stretch the silicone round button, and then the screen appears. This sliding screen mode helps to protect the screen and is more suitable for transportation.3. Simple operation: the screen amplifier doubles the screen size, so you can make the most of movies and videos on your HD smartphone.",
                "price": 5999.99,
                "image": "http://127.0.0.1:8000/media/images/12inch_3D_Mobile_Phone_Screen_Magnifier_HD_Video_Amplifier_Stand_Bracket.jpg",
                "date_created": "2022-07-08T13:59:04.084206Z",
                "itemCount": 3
            },
            {
                "id": 7,
                "category": "Accessories",
                "name": "Universel Sports Bluetooth Headset B05 White",
                "description": "Connectivity: Bluetooth wirelessTransmission range: 10 metersModel: music headphones.Wireless technology: BluetoothFitted Design: HeadbandType: helmetEarphone design: ear cushion (over the ear)Channel: StereoWhether single or binaural: bilateral stereoSpeaker Size: 40mmStandby time: 5-8 minutes auto-off",
                "price": 6900,
                "image": "http://127.0.0.1:8000/media/images/Universel_Sports_Bluetooth_Headset_B05_White.jpg",
                "date_created": "2022-07-08T13:53:18.308720Z",
                "itemCount": 1
            },
            {
                "id": 8,
                "category": "Accessories",
                "name": "Aihontai Gaming Headsets",
                "description": "Professional LED LIGHT Computer Gaming Headset For PS4 Xbox One PC PHONE Cable length: about 200cm Item Type: Gaming Headset Mic dimension: 6.0 * 5.0mm LED working voltage: DC5V ± 5% Socket: USB plugs for microphone and headphones / audio Micro directivity: Omnidirectional Type: over ear Work interface: USB + 3.5mm stereo Speaker diameter: 40mm Sensitivity: 105db ± 3db Frequency response: 20Hz-20KHz Cable length: 2.0M Impedance: 32 ohms The package includes: 1x gaming headset",
                "price": 8599.99,
                "image": "http://127.0.0.1:8000/media/images/Aihontai_Gaming_Headsets_.jpg",
                "date_created": "2022-07-08T13:54:51.061448Z",
                "itemCount": 2
            }
        ],
        "cost": 22399.99,
        "customer": "michaelikoko.o@gmail.com",
        "status": "pending",
        "order_number": "8627034895",
        "date_ordered": "2022-07-26T18:57:20.629110Z"
    }
]

export default data